# Generated by Django 2.2.5 on 2019-09-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_orcamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_item', models.IntegerField()),
                ('codigo_orcamento', models.IntegerField()),
                ('codigo_produto', models.IntegerField()),
                ('quantidade', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
            ],
        ),
    ]
